package dev.glisseo.izar.compiler;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.math.BigDecimal;
import java.net.URL;
import java.net.URLClassLoader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.tools.JavaCompiler;
import javax.tools.ToolProvider;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Compiles a generated query and mutation configured with two custom scalar mappings ({@code
 * DateTime} through {@code izar-scalars}' {@link dev.glisseo.izar.scalars.InstantScalarCodec}, and
 * an application-supplied {@code Money} through the {@link
 * dev.glisseo.izar.compiler.fixtures.MoneyScalarCodec} fixture, which depends on neither Apollo,
 * Kotlin, nor {@code izar-scalars} itself) and drives real generated bytecode through both
 * directions. Covers issue 06's acceptance criteria: a plain scalar field, a nested output object's
 * scalar field, a nullable list of a nullable scalar, a nested input object's scalar field, and a
 * clear decode failure for an invalid wire value.
 */
class CompiledScalarRoundTripTest {

    private static final List<ScalarMapping> SCALAR_MAPPINGS =
            List.of(
                    new ScalarMapping("DateTime", "java.time.Instant", "dev.glisseo.izar.scalars.InstantScalarCodec"),
                    new ScalarMapping(
                            "Money", "java.math.BigDecimal", "dev.glisseo.izar.compiler.fixtures.MoneyScalarCodec"));

    @Test
    void decodesAPlainFieldANestedObjectFieldAndANullableListOfCustomScalars(@TempDir Path tempDir)
            throws Exception {
        Path schema = tempDir.resolve("schema.graphqls");
        Path operation = tempDir.resolve("GetBookWithScalars.graphql");
        Files.writeString(schema, Fixtures.BOOK_SCHEMA_WITH_SCALARS);
        Files.writeString(operation, Fixtures.GET_BOOK_WITH_SCALARS_OPERATION);

        Path generatedSources = tempDir.resolve("generated-sources");
        new OperationCompiler()
                .generate(List.of(schema), List.of(operation), generatedSources, "generated.book", SCALAR_MAPPINGS);

        Path javaFile =
                generatedSources.resolve("generated").resolve("book").resolve("GetBookWithScalarsQuery.java");
        Path classesOutput = tempDir.resolve("classes");
        Files.createDirectories(classesOutput);
        compile(javaFile, classesOutput);

        Map<String, Object> edition = Map.of("releasedAt", "1965-08-01T00:00:00Z");
        List<Object> notableDates = Arrays.asList("2020-01-01T00:00:00Z", null);
        Map<String, Object> book = new HashMap<>();
        book.put("title", "Dune");
        book.put("publishedAt", "2026-09-11T10:15:30Z");
        book.put("price", "19.99");
        book.put("notableDates", notableDates);
        book.put("edition", edition);
        Map<String, Object> data = Map.of("book", book);

        try (URLClassLoader loader =
                new URLClassLoader(new URL[] {classesOutput.toUri().toURL()}, getClass().getClassLoader())) {
            Class<?> operationClass = Class.forName("generated.book.GetBookWithScalarsQuery", true, loader);
            Object operationInstance = operationClass.getDeclaredConstructor().newInstance();

            Object decoded = operationClass.getMethod("decode", Object.class).invoke(operationInstance, data);
            Object decodedBook = decoded.getClass().getMethod("book").invoke(decoded);

            assertThat(decodedBook.getClass().getMethod("publishedAt").invoke(decodedBook))
                    .isEqualTo(Instant.parse("2026-09-11T10:15:30Z"));
            assertThat(decodedBook.getClass().getMethod("price").invoke(decodedBook))
                    .isEqualTo(new BigDecimal("19.99"));

            @SuppressWarnings("unchecked")
            List<Object> decodedDates = (List<Object>) decodedBook.getClass().getMethod("notableDates").invoke(decodedBook);
            assertThat(decodedDates).containsExactly(Instant.parse("2020-01-01T00:00:00Z"), null);

            Object decodedEdition = decodedBook.getClass().getMethod("edition").invoke(decodedBook);
            assertThat(decodedEdition.getClass().getMethod("releasedAt").invoke(decodedEdition))
                    .isEqualTo(Instant.parse("1965-08-01T00:00:00Z"));
        }
    }

    @Test
    void decodeFailsUsefullyForAnInvalidCustomScalarValue(@TempDir Path tempDir) throws Exception {
        Path schema = tempDir.resolve("schema.graphqls");
        Path operation = tempDir.resolve("GetBookWithScalars.graphql");
        Files.writeString(schema, Fixtures.BOOK_SCHEMA_WITH_SCALARS);
        Files.writeString(operation, Fixtures.GET_BOOK_WITH_SCALARS_OPERATION);

        Path generatedSources = tempDir.resolve("generated-sources");
        new OperationCompiler()
                .generate(List.of(schema), List.of(operation), generatedSources, "generated.book", SCALAR_MAPPINGS);

        Path javaFile =
                generatedSources.resolve("generated").resolve("book").resolve("GetBookWithScalarsQuery.java");
        Path classesOutput = tempDir.resolve("classes");
        Files.createDirectories(classesOutput);
        compile(javaFile, classesOutput);

        Map<String, Object> book = new HashMap<>();
        book.put("title", "Dune");
        book.put("publishedAt", "not-a-date");
        Map<String, Object> data = Map.of("book", book);

        try (URLClassLoader loader =
                new URLClassLoader(new URL[] {classesOutput.toUri().toURL()}, getClass().getClassLoader())) {
            Class<?> operationClass = Class.forName("generated.book.GetBookWithScalarsQuery", true, loader);
            Object operationInstance = operationClass.getDeclaredConstructor().newInstance();
            Method decode = operationClass.getMethod("decode", Object.class);

            assertThatThrownBy(() -> decode.invoke(operationInstance, data))
                    .isInstanceOf(InvocationTargetException.class)
                    .cause()
                    .isInstanceOf(IllegalArgumentException.class)
                    .hasMessageContaining("DateTime")
                    .hasMessageContaining("not-a-date");
        }
    }

    @Test
    void encodesAPlainVariableANestedInputObjectAndANullableListOfCustomScalars(@TempDir Path tempDir)
            throws Exception {
        Path schema = tempDir.resolve("schema.graphqls");
        Path operation = tempDir.resolve("CreateBookWithScalars.graphql");
        Files.writeString(schema, Fixtures.BOOK_SCHEMA_WITH_SCALARS);
        Files.writeString(operation, Fixtures.CREATE_BOOK_WITH_SCALARS_OPERATION);

        Path generatedSources = tempDir.resolve("generated-sources");
        new OperationCompiler()
                .generate(List.of(schema), List.of(operation), generatedSources, "generated.book", SCALAR_MAPPINGS);

        Path javaFile =
                generatedSources.resolve("generated").resolve("book").resolve("CreateBookWithScalarsMutation.java");
        Path classesOutput = tempDir.resolve("classes");
        Files.createDirectories(classesOutput);
        compile(javaFile, classesOutput);

        try (URLClassLoader loader =
                new URLClassLoader(new URL[] {classesOutput.toUri().toURL()}, getClass().getClassLoader())) {
            Class<?> mutationClass = Class.forName("generated.book.CreateBookWithScalarsMutation", true, loader);
            Class<?> bookInputClass =
                    Class.forName("generated.book.CreateBookWithScalarsMutation$BookInput", true, loader);
            Class<?> editionInputClass =
                    Class.forName("generated.book.CreateBookWithScalarsMutation$EditionInput", true, loader);

            Object editionBuilder = invoke(editionInputClass, "builder");
            editionBuilder = invoke(editionBuilder, "releasedAt", Instant.class, Instant.parse("1965-08-01T00:00:00Z"));
            Object editionInput = invoke(editionBuilder, "build");

            Object bookInputBuilder = invoke(bookInputClass, "builder");
            bookInputBuilder = invoke(bookInputBuilder, "title", String.class, "Dune");
            bookInputBuilder =
                    invoke(bookInputBuilder, "publishedAt", Instant.class, Instant.parse("2026-09-11T10:15:30Z"));
            bookInputBuilder = invoke(bookInputBuilder, "price", BigDecimal.class, new BigDecimal("19.99"));
            List<Object> notableDates = Arrays.asList(Instant.parse("2020-01-01T00:00:00Z"), null);
            bookInputBuilder = invoke(bookInputBuilder, "notableDates", List.class, notableDates);
            bookInputBuilder = invoke(bookInputBuilder, "edition", editionInputClass, editionInput);
            Object bookInput = invoke(bookInputBuilder, "build");

            @SuppressWarnings("unchecked")
            Map<String, Object> encoded = (Map<String, Object>) invoke(bookInput, "encode");
            assertThat(encoded).containsEntry("title", "Dune");
            assertThat(encoded).containsEntry("publishedAt", "2026-09-11T10:15:30Z");
            assertThat(encoded).containsEntry("price", "19.99");

            @SuppressWarnings("unchecked")
            List<Object> encodedDates = (List<Object>) encoded.get("notableDates");
            assertThat(encodedDates).containsExactly("2020-01-01T00:00:00Z", null);

            @SuppressWarnings("unchecked")
            Map<String, Object> encodedEdition = (Map<String, Object>) encoded.get("edition");
            assertThat(encodedEdition).containsEntry("releasedAt", "1965-08-01T00:00:00Z");

            Object mutationBuilder = invoke(mutationClass, "builder");
            mutationBuilder = invoke(mutationBuilder, "input", bookInputClass, bookInput);
            Object mutation = invoke(mutationBuilder, "build");

            @SuppressWarnings("unchecked")
            Map<String, Object> variables = (Map<String, Object>) invoke(mutation, "variables");
            assertThat(variables).containsOnlyKeys("input");
            assertThat(variables.get("input")).isEqualTo(encoded);
        }
    }

    private static Object invoke(Class<?> ownerClass, String methodName) throws Exception {
        Method method = ownerClass.getDeclaredMethod(methodName);
        method.setAccessible(true);
        return method.invoke(null);
    }

    private static Object invoke(Object receiver, String methodName) throws Exception {
        Method method = receiver.getClass().getDeclaredMethod(methodName);
        method.setAccessible(true);
        return method.invoke(receiver);
    }

    private static Object invoke(Object receiver, String methodName, Class<?> paramType, Object arg) throws Exception {
        Method method = receiver.getClass().getDeclaredMethod(methodName, paramType);
        method.setAccessible(true);
        return method.invoke(receiver, arg);
    }

    private static void compile(Path javaFile, Path classesOutput) throws IOException {
        JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
        ByteArrayOutputStream diagnostics = new ByteArrayOutputStream();
        int result =
                compiler.run(
                        null,
                        new PrintStream(diagnostics),
                        new PrintStream(diagnostics),
                        "-d",
                        classesOutput.toString(),
                        "-cp",
                        System.getProperty("java.class.path"),
                        javaFile.toString());
        assertThat(result).as("javac output:%n%s", diagnostics).isZero();
    }
}
