package dev.glisseo.izar.compiler;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.net.URL;
import java.net.URLClassLoader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.tools.JavaCompiler;
import javax.tools.ToolProvider;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Compiles a generated mutation with {@code javac} and drives its variable builders through
 * reflection, so these assertions exercise real generated bytecode rather than generated source
 * text. Covers omission versus explicit null versus a
 * usable default, required-input failure before any request, and defensive copying that neither
 * a builder nor a supplied collection can undo after {@code build()}.
 */
class CompiledVariableBuilderTest {

    private Class<?> mutationClass;
    private Class<?> bookInputClass;
    private Class<?> authorInputClass;
    private Class<?> genreEnumClass;

    @Test
    void buildsAndExecutesUsingVariablesNestedInputObjectsEnumsAndListsOfInputs(@TempDir Path tempDir)
            throws Exception {
        load(tempDir);

        Object minimalBookInput = bookInputBuilder().withTitle("Dune").build();
        @SuppressWarnings("unchecked")
        Map<String, Object> encoded = (Map<String, Object>) invoke(minimalBookInput, "encode");

        assertThat(encoded).containsEntry("title", "Dune");
        assertThat(encoded).doesNotContainKey("pageCount");
        assertThat(encoded).doesNotContainKey("genre");
        assertThat(encoded).doesNotContainKey("tags");
        assertThat(encoded).doesNotContainKey("coAuthors");
    }

    @Test
    void distinguishesOmissionFromExplicitNull(@TempDir Path tempDir) throws Exception {
        load(tempDir);

        Object untouched = bookInputBuilder().withTitle("Dune").build();
        Object explicitNull = bookInputBuilder().withTitle("Dune").with("pageCount", int.class, null).build();

        assertThat(encodedOf(untouched)).doesNotContainKey("pageCount");
        assertThat(encodedOf(explicitNull)).containsKey("pageCount");
        assertThat(encodedOf(explicitNull).get("pageCount")).isNull();
    }

    @Test
    void omitsAnUntouchedFieldWithAUsableSchemaDefaultButRequiresOneWithout(@TempDir Path tempDir)
            throws Exception {
        load(tempDir);

        // 'genre' has a schema default: omitting it must not fail.
        Object withDefaultedGenre = bookInputBuilder().withTitle("Dune").build();
        assertThat(encodedOf(withDefaultedGenre)).doesNotContainKey("genre");

        // 'title' has no default: omitting it must fail before any request is built.
        assertThatThrownBy(() -> bookInputBuilder().build())
                .isInstanceOf(InvocationTargetException.class)
                .cause()
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("title");
    }

    @Test
    void encodesAnEnumVariableAsItsGraphQlName(@TempDir Path tempDir) throws Exception {
        load(tempDir);

        Object nonfiction = genreEnumClass.getField("NONFICTION").get(null);
        Object bookInput =
                invoke(newBuilder(bookInputClass), "genre", genreEnumClass, nonfiction);
        Object built = invoke(bookInput, "title", String.class, "Dune");
        built = invoke(built, "build");

        assertThat(encodedOf(built)).containsEntry("genre", "NONFICTION");
    }

    @Test
    void preservesNullListElementsAndIsolatesTheBuiltValueFromLaterSourceMutation(@TempDir Path tempDir)
            throws Exception {
        load(tempDir);

        List<String> tags = new ArrayList<>();
        tags.add("sci-fi");
        tags.add(null);

        Object builder = newBuilder(bookInputClass);
        builder = invoke(builder, "title", String.class, "Dune");
        builder = invoke(builder, "tags", List.class, tags);
        Object built = invoke(builder, "build");

        @SuppressWarnings("unchecked")
        List<Object> encodedTags = (List<Object>) encodedOf(built).get("tags");
        assertThat(encodedTags).containsExactly("sci-fi", null);

        // Mutating the caller's source list after the setter must not change the built value.
        tags.add("late-addition");
        @SuppressWarnings("unchecked")
        List<Object> tagsAccessor = (List<Object>) invoke(built, "tags");
        assertThat(tagsAccessor).containsExactly("sci-fi", null);

        // The exposed collection itself cannot mutate the built value.
        assertThatThrownBy(() -> tagsAccessor.add("nope")).isInstanceOf(UnsupportedOperationException.class);
    }

    @Test
    void encodesAListOfNestedInputObjectsThroughEachElementsOwnEncoding(@TempDir Path tempDir)
            throws Exception {
        load(tempDir);

        Object author = invoke(newBuilder(authorInputClass), "name", String.class, "Frank Herbert");
        author = invoke(author, "build");

        Object builder = newBuilder(bookInputClass);
        builder = invoke(builder, "title", String.class, "Dune");
        builder = invoke(builder, "coAuthors", List.class, List.of(author));
        Object built = invoke(builder, "build");

        @SuppressWarnings("unchecked")
        List<Object> encodedCoAuthors = (List<Object>) encodedOf(built).get("coAuthors");
        assertThat(encodedCoAuthors).hasSize(1);
        @SuppressWarnings("unchecked")
        Map<String, Object> encodedAuthor = (Map<String, Object>) encodedCoAuthors.get(0);
        assertThat(encodedAuthor).containsEntry("name", "Frank Herbert");
    }

    @Test
    void rejectsANullElementInAListWhoseSchemaElementTypeIsNonNull(@TempDir Path tempDir) throws Exception {
        load(tempDir);

        // 'coAuthors' is typed '[AuthorInput!]': the list itself may be null or omitted, but an
        // element that is present must not be null. Defeat generics with a raw list, the way a
        // caller reusing a mutable collection built elsewhere might end up doing by accident.
        List<Object> coAuthorsWithANull = new ArrayList<>();
        coAuthorsWithANull.add(null);

        Object builder = newBuilder(bookInputClass);
        builder = invoke(builder, "title", String.class, "Dune");
        builder = invoke(builder, "coAuthors", List.class, coAuthorsWithANull);
        Object readyToBuild = builder;

        // The failure must happen at build(), before any request could be sent, not silently
        // pass the null through to the wire.
        assertThatThrownBy(() -> invoke(readyToBuild, "build"))
                .isInstanceOf(InvocationTargetException.class)
                .cause()
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("null");
    }

    @Test
    void requiresTheTopLevelOperationVariableBeforeBuildingWhenItHasNoDefault(@TempDir Path tempDir)
            throws Exception {
        load(tempDir);

        Object mutationBuilder = invoke(mutationClass, "builder");
        assertThatThrownBy(() -> invoke(mutationBuilder, "build"))
                .isInstanceOf(InvocationTargetException.class)
                .cause()
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("input");
    }

    @Test
    void roundTripsAFullyBuiltOperationThroughItsVariablesMap(@TempDir Path tempDir) throws Exception {
        load(tempDir);

        Object bookInput = invoke(bookInputBuilder().withTitle("Dune").builder, "build");
        Object mutationBuilder = invoke(mutationClass, "builder");
        mutationBuilder = invoke(mutationBuilder, "input", bookInputClass, bookInput);
        Object mutation = invoke(mutationBuilder, "build");

        @SuppressWarnings("unchecked")
        Map<String, Object> variables = (Map<String, Object>) invoke(mutation, "variables");
        assertThat(variables).containsOnlyKeys("input");
        @SuppressWarnings("unchecked")
        Map<String, Object> encodedInput = (Map<String, Object>) variables.get("input");
        assertThat(encodedInput).containsEntry("title", "Dune");
    }

    private void load(Path tempDir) throws Exception {
        Path schema = tempDir.resolve("schema.graphqls");
        Path operation = tempDir.resolve("CreateBook.graphql");
        Files.writeString(schema, Fixtures.BOOK_SCHEMA_WITH_MUTATION);
        Files.writeString(operation, Fixtures.CREATE_BOOK_OPERATION);

        Path generatedSources = tempDir.resolve("generated-sources");
        new OperationCompiler().generate(List.of(schema), List.of(operation), generatedSources, "generated.book");

        Path javaFile =
                generatedSources.resolve("generated").resolve("book").resolve("CreateBookMutation.java");
        Path classesOutput = tempDir.resolve("classes");
        Files.createDirectories(classesOutput);
        compile(javaFile, classesOutput);

        URLClassLoader loader =
                new URLClassLoader(new URL[] {classesOutput.toUri().toURL()}, getClass().getClassLoader());
        mutationClass = Class.forName("generated.book.CreateBookMutation", true, loader);
        bookInputClass = Class.forName("generated.book.CreateBookMutation$BookInput", true, loader);
        authorInputClass = Class.forName("generated.book.CreateBookMutation$AuthorInput", true, loader);
        genreEnumClass = Class.forName("generated.book.CreateBookMutation$Genre", true, loader);
    }

    @SuppressWarnings("unchecked")
    private Map<String, Object> encodedOf(Object builtInput) throws Exception {
        return (Map<String, Object>) invoke(builtInput, "encode");
    }

    private BookInputSteps bookInputBuilder() throws Exception {
        return new BookInputSteps(newBuilder(bookInputClass));
    }

    /** A small fluent wrapper so reflective builder calls in tests read naturally. */
    private final class BookInputSteps {
        Object builder;

        BookInputSteps(Object builder) {
            this.builder = builder;
        }

        BookInputSteps withTitle(String title) throws Exception {
            builder = invoke(builder, "title", String.class, title);
            return this;
        }

        BookInputSteps with(String property, Class<?> paramType, Object value) throws Exception {
            Class<?> setterParamType = paramType.isPrimitive() ? box(paramType) : paramType;
            builder = invoke(builder, property, setterParamType, value);
            return this;
        }

        Object build() throws Exception {
            return invoke(builder, "build");
        }
    }

    private static Class<?> box(Class<?> primitive) {
        if (primitive == int.class) {
            return Integer.class;
        }
        throw new IllegalArgumentException("Unhandled primitive: " + primitive);
    }

    private static Object newBuilder(Class<?> ownerClass) throws Exception {
        return invoke(ownerClass, "builder");
    }

    private static Object invoke(Class<?> ownerClass, String methodName) throws Exception {
        Method method = ownerClass.getDeclaredMethod(methodName);
        method.setAccessible(true);
        return method.invoke(null);
    }

    private static Object invoke(Object receiver, String methodName) throws Exception {
        // encode() is deliberately package-private; loaded through a different ClassLoader than
        // this test, so even same-package access needs an explicit override here.
        Method method = receiver.getClass().getDeclaredMethod(methodName);
        method.setAccessible(true);
        return method.invoke(receiver);
    }

    private static Object invoke(Object receiver, String methodName, Class<?> paramType, Object arg)
            throws Exception {
        Method method = receiver.getClass().getDeclaredMethod(methodName, paramType);
        method.setAccessible(true);
        return method.invoke(receiver, arg);
    }

    private static void compile(Path javaFile, Path classesOutput) throws IOException {
        JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
        ByteArrayOutputStream diagnostics = new ByteArrayOutputStream();
        int result =
                compiler.run(
                        null,
                        new PrintStream(diagnostics),
                        new PrintStream(diagnostics),
                        "-d",
                        classesOutput.toString(),
                        "-cp",
                        System.getProperty("java.class.path"),
                        javaFile.toString());
        assertThat(result).as("javac output:%n%s", diagnostics).isZero();
    }
}
