package dev.glisseo.izar.compiler.internal.generate;

import dev.glisseo.izar.compiler.internal.naming.JavaIdentifiers;
import dev.glisseo.izar.compiler.internal.naming.JavaLiterals;
import dev.glisseo.izar.compiler.internal.scalar.BuiltinScalar;
import dev.glisseo.izar.compiler.internal.scalar.CustomScalarType;
import dev.glisseo.izar.compiler.internal.scalar.ScalarType;
import dev.glisseo.izar.compiler.internal.selection.FieldSelection;
import dev.glisseo.izar.compiler.internal.selection.FieldShape;
import dev.glisseo.izar.compiler.internal.selection.FragmentInterface;
import dev.glisseo.izar.compiler.internal.selection.ObjectSelection;
import dev.glisseo.izar.compiler.internal.selection.OutputEnumType;
import dev.glisseo.izar.compiler.internal.selection.PolymorphicBranch;
import dev.glisseo.izar.compiler.internal.selection.PolymorphicSelection;
import dev.glisseo.izar.compiler.internal.variable.InputEnumType;
import dev.glisseo.izar.compiler.internal.variable.InputFieldDefinition;
import dev.glisseo.izar.compiler.internal.variable.InputObjectType;
import dev.glisseo.izar.compiler.internal.variable.InputShape;
import dev.glisseo.izar.compiler.internal.variable.VariableAnalyzer;
import dev.glisseo.izar.operation.GraphQlOperationKind;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.jspecify.annotations.Nullable;

/**
 * Renders an operation's {@link ObjectSelection} tree into Java source text.
 *
 * <p>Every generated record is a direct sibling inside the operation class rather than lexically
 * nested inside the record that selected it: simpler to render, and {@code
 * dev.glisseo.izar.compiler.internal.selection.SelectionAnalyzer} already guarantees every generated type
 * name is unique across the whole operation. Output is a pure function of its inputs, so identical
 * selections always produce byte-identical source.
 *
 * <p>A {@link PolymorphicSelection} renders as a sealed interface plus one sibling record per
 * branch (including the {@code Unrecognized} catch-all): each branch is an ordinary {@link
 * ObjectSelection}, so the same per-type decode/record rendering used for plain object selections
 * covers it too, with an added {@code implements} clause. Every generated {@code decodeX} method
 * takes {@code DecodingPolicy} as a second parameter and passes it on to every nested {@code
 * decodeX} call it makes so a nested selection can apply the policy when decoding enum or
 * polymorphic fields.
 */
final class IzarSourceGenerator {

    private IzarSourceGenerator() {}

    /**
     * Renders a leaf-only fragment's {@link FragmentInterface} as its own top-level file: unlike
     * every other generated type, it is not a sibling inside an operation class, since it is meant
     * to be {@code implements}ed by records across many operation classes in the same package. See
     * {@code dev.glisseo.izar.compiler.internal.selection.FragmentInterfaceAnalyzer} for which fragments
     * qualify.
     */
    public static String generateFragmentInterface(String packageName, FragmentInterface fragmentInterface) {
        StringBuilder out = new StringBuilder();
        out.append("package ").append(packageName).append(";\n\n");
        out.append("import java.util.List;\n");
        out.append("import org.jspecify.annotations.NullMarked;\n");
        out.append("import org.jspecify.annotations.Nullable;\n");
        out.append('\n');
        out.append("/** Generated by Izar from fragment '")
                .append(fragmentInterface.javaTypeName())
                .append("'. Do not edit. */\n");
        out.append("@NullMarked\n");
        out.append("public interface ").append(fragmentInterface.javaTypeName()).append(" {\n\n");
        List<FieldSelection> fields = fragmentInterface.fields();
        for (int i = 0; i < fields.size(); i++) {
            out.append("    ").append(fieldTypeAndName(fields.get(i))).append("();\n");
            out.append(i < fields.size() - 1 ? "\n" : "");
        }
        out.append("}\n");
        return out.toString();
    }

    public static String generate(
            String packageName,
            String className,
            String operationName,
            String documentText,
            String operationId,
            GraphQlOperationKind operationKind,
            ObjectSelection root,
            List<OutputEnumType> outputEnumTypes,
            VariableAnalyzer.Result variables) {
        GeneratedSelections flattened = GeneratedSelections.from(root);
        boolean hasVariables = !variables.variables().isEmpty();

        StringBuilder out = new StringBuilder();
        out.append("package ").append(packageName).append(";\n\n");
        out.append("import dev.glisseo.izar.operation.DecodingPolicy;\n");
        out.append("import dev.glisseo.izar.operation.GraphQlDecoding;\n");
        out.append("import dev.glisseo.izar.operation.GraphQlEncoding;\n");
        out.append("import dev.glisseo.izar.operation.GraphQlOperation;\n");
        out.append("import dev.glisseo.izar.operation.GraphQlOperationKind;\n");
        out.append("import dev.glisseo.izar.operation.ScalarCodec;\n");
        out.append("import java.util.Collections;\n");
        out.append("import java.util.LinkedHashMap;\n");
        out.append("import java.util.List;\n");
        out.append("import java.util.Map;\n");
        out.append("import org.jspecify.annotations.NullMarked;\n");
        out.append("import org.jspecify.annotations.Nullable;\n");
        out.append('\n');
        out.append("/** Generated by Izar from operation '").append(operationName).append("'. Do not edit. */\n");
        out.append("@NullMarked\n");
        out.append("public final class ")
                .append(className)
                .append(" implements GraphQlOperation<")
                .append(className)
                .append(".Data> {\n\n");

        SourceGeneratorSupport.appendOperationConstants(out, operationName, documentText, operationId, operationKind);
        List<CustomScalarType> customScalars = collectCustomScalars(flattened.objectSelections(), variables);
        SourceGeneratorSupport.appendScalarCodecFields(out, customScalars);

        if (hasVariables) {
            InputSourceGenerator.appendOperationVariableMembers(out, className, variables.variables());
        }

        SourceGeneratorSupport.appendOperationMethods(out, hasVariables);

        out.append("    @Override\n    public Data decode(@Nullable Object data, DecodingPolicy policy) {\n        return decode")
                .append(root.javaTypeName())
                .append("(GraphQlDecoding.asMap(data), policy);\n    }\n\n");

        for (ObjectSelection type : flattened.objectSelections()) {
            appendDecodeMethod(out, type);
        }
        for (PolymorphicSelection polymorphic : flattened.polymorphicSelections()) {
            appendPolymorphicDecodeMethod(out, polymorphic);
        }
        for (ObjectSelection type : flattened.objectSelections()) {
            appendRecord(
                    out,
                    type,
                    flattened.implementsInterfaceByTypeName().get(type.javaTypeName()));
        }
        for (PolymorphicSelection polymorphic : flattened.polymorphicSelections()) {
            appendPolymorphicInterface(out, polymorphic);
        }
        for (OutputEnumType enumType : outputEnumTypes) {
            appendOutputEnumType(out, enumType);
        }
        for (InputEnumType enumType : variables.enumTypes()) {
            InputSourceGenerator.appendEnumType(out, enumType);
        }
        for (InputObjectType inputObjectType : variables.inputObjectTypes()) {
            InputSourceGenerator.appendInputObjectType(out, inputObjectType);
        }

        out.append("}\n");
        return out.toString();
    }

    /**
     * Every distinct custom scalar reachable from either the output selection tree or the
     * variable/input-object tree, in first-encountered order. A nested object field or
     * polymorphic branch's own scalar fields are found through its own entry in {@code
     * objectSelections} (already flattened breadth-first), so only list wrapping needs unwrapping
     * here; likewise a nested input object's fields are found through {@code
     * variables.inputObjectTypes()} directly, not by recursing into {@link
     * InputShape.InputObjectShape}.
     */
    private static List<CustomScalarType> collectCustomScalars(
            List<ObjectSelection> objectSelections, VariableAnalyzer.Result variables) {
        Map<String, CustomScalarType> byGraphqlName = new LinkedHashMap<>();
        for (ObjectSelection type : objectSelections) {
            for (FieldSelection field : type.fields()) {
                collectFromFieldShape(field.shape(), byGraphqlName);
            }
        }
        for (CustomScalarType scalar : InputSourceGenerator.collectCustomScalars(variables)) {
            byGraphqlName.putIfAbsent(scalar.graphqlName(), scalar);
        }
        return List.copyOf(byGraphqlName.values());
    }

    private static void collectFromFieldShape(FieldShape shape, Map<String, CustomScalarType> byGraphqlName) {
        switch (shape) {
            case FieldShape.ScalarField scalar -> {
                if (scalar.scalar() instanceof CustomScalarType custom) {
                    byGraphqlName.putIfAbsent(custom.graphqlName(), custom);
                }
            }
            case FieldShape.ListField list -> collectFromFieldShape(list.elementShape(), byGraphqlName);
            case FieldShape.ObjectField ignored -> {}
            case FieldShape.PolymorphicField ignored -> {}
            case FieldShape.EnumField ignored -> {}
        }
    }

    private static void appendDecodeMethod(StringBuilder out, ObjectSelection type) {
        out.append("    private static ")
                .append(type.javaTypeName())
                .append(" decode")
                .append(type.javaTypeName())
                .append("(Map<String, Object> map, DecodingPolicy policy) {\n");

        List<String> constructorArgs = new ArrayList<>();
        for (FieldSelection field : type.fields()) {
            String valueVar = JavaIdentifiers.fieldIdentifier(field.responseName()) + "Value";
            out.append("        Object ")
                    .append(valueVar)
                    .append(" = map.get(")
                    .append(JavaLiterals.quote(field.responseName()))
                    .append(");\n");
            constructorArgs.add(decodeExpression(field.shape(), valueVar, 0));
        }

        out.append("        return new ").append(type.javaTypeName()).append('(');
        out.append(constructorArgs.isEmpty() ? "" : "\n");
        for (int i = 0; i < constructorArgs.size(); i++) {
            out.append("            ").append(constructorArgs.get(i));
            out.append(i < constructorArgs.size() - 1 ? ",\n" : "\n");
        }
        out.append(constructorArgs.isEmpty() ? "" : "        ");
        out.append(");\n");
        out.append("    }\n\n");
    }

    private static void appendPolymorphicDecodeMethod(StringBuilder out, PolymorphicSelection polymorphic) {
        out.append("    private static ")
                .append(polymorphic.javaTypeName())
                .append(" decode")
                .append(polymorphic.javaTypeName())
                .append("(Map<String, Object> map, DecodingPolicy policy) {\n");
        out.append("        String typename = GraphQlDecoding.asString(map.get(")
                .append(JavaLiterals.quote(polymorphic.discriminatorResponseKey()))
                .append("));\n");
        out.append("        return switch (typename) {\n");
        for (PolymorphicBranch branch : polymorphic.branches()) {
            out.append("            case ")
                    .append(JavaLiterals.quote(branch.graphqlTypeName()))
                    .append(" -> decode")
                    .append(branch.selection().javaTypeName())
                    .append("(map, policy);\n");
        }
        out.append("            default -> {\n");
        out.append("                if (policy == DecodingPolicy.STRICT) {\n");
        out.append("                    throw new IllegalArgumentException(")
                .append(JavaLiterals.quote("Expected a known concrete type for '" + polymorphic.javaTypeName() + "', got '"))
                .append(" + typename + ")
                .append(JavaLiterals.quote("'."))
                .append(");\n");
        out.append("                }\n");
        out.append("                yield decode")
                .append(polymorphic.unrecognizedBranch().javaTypeName())
                .append("(map, policy);\n");
        out.append("            }\n");
        out.append("        };\n");
        out.append("    }\n\n");
    }

    private static String decodeExpression(FieldShape shape, String valueVar, int depth) {
        String nonNullExpression = nonNullDecodeExpression(shape, valueVar, depth);
        return shape.nullable() ? (valueVar + " == null ? null : " + nonNullExpression) : nonNullExpression;
    }

    /**
     * The decode expression for {@code valueVar} assuming it is already known non-null: used only
     * for a field whose shape is itself non-null. A list element's own decode expression still
     * goes through {@link #decodeExpression}, not this method, since {@link
     * dev.glisseo.izar.operation.GraphQlDecoding#decodeList} passes every element through
     * (including {@code null} ones) and relies on the generated element lambda to null-check when
     * the schema permits a {@code null} element.
     */
    private static String nonNullDecodeExpression(FieldShape shape, String valueVar, int depth) {
        return switch (shape) {
            case FieldShape.ScalarField scalar -> scalarDecodeExpression(scalar.scalar(), valueVar);
            case FieldShape.EnumField enumField -> enumDecodeExpression(enumField, valueVar);
            case FieldShape.ObjectField object ->
                    "decode"
                            + object.selection().javaTypeName()
                            + "(GraphQlDecoding.asMap("
                            + valueVar
                            + "), policy)";
            case FieldShape.PolymorphicField polymorphic ->
                    "decode"
                            + polymorphic.selection().javaTypeName()
                            + "(GraphQlDecoding.asMap("
                            + valueVar
                            + "), policy)";
            case FieldShape.ListField list -> {
                String elementVar = "element" + depth;
                yield "GraphQlDecoding.decodeList("
                        + valueVar
                        + ", ("
                        + elementVar
                        + ") -> "
                        + decodeExpression(list.elementShape(), elementVar, depth + 1)
                        + ")";
            }
        };
    }

    private static String scalarDecodeExpression(ScalarType scalar, String valueVar) {
        return switch (scalar) {
            case BuiltinScalar builtin -> "GraphQlDecoding." + builtin.decodeMethodName() + "(" + valueVar + ")";
            case CustomScalarType custom ->
                    "GraphQlDecoding.decodeScalar("
                            + valueVar
                            + ", "
                            + custom.codecFieldName()
                            + ", "
                            + JavaLiterals.quote(custom.graphqlName())
                            + ")";
        };
    }

    private static String enumDecodeExpression(FieldShape.EnumField enumField, String valueVar) {
        String javaTypeName = enumField.enumType().javaTypeName();
        return "GraphQlDecoding.decodeEnum("
                + valueVar
                + ", "
                + javaTypeName
                + ".Known.class, known -> known, "
                + javaTypeName
                + ".Unrecognized::new, "
                + JavaLiterals.quote(enumField.enumType().graphqlName())
                + ", policy)";
    }

    private static void appendRecord(
            StringBuilder out, ObjectSelection type, @Nullable String polymorphicInterface) {
        out.append("    public record ").append(type.javaTypeName()).append('(');
        List<FieldSelection> fields = type.fields();
        out.append(fields.isEmpty() ? "" : "\n");
        for (int i = 0; i < fields.size(); i++) {
            out.append("            ").append(fieldTypeAndName(fields.get(i)));
            out.append(i < fields.size() - 1 ? ",\n" : "\n");
        }
        out.append(fields.isEmpty() ? "" : "    ");
        out.append(')');
        List<String> interfaces = new ArrayList<>(type.implementsFragments());
        if (polymorphicInterface != null) {
            interfaces.add(polymorphicInterface);
        }
        if (!interfaces.isEmpty()) {
            out.append(" implements ").append(String.join(", ", interfaces));
        }
        out.append(" {}\n\n");
    }

    private static void appendPolymorphicInterface(StringBuilder out, PolymorphicSelection polymorphic) {
        List<String> permitted = new ArrayList<>();
        for (PolymorphicBranch branch : polymorphic.branches()) {
            permitted.add(branch.selection().javaTypeName());
        }
        permitted.add(polymorphic.unrecognizedBranch().javaTypeName());

        out.append("    public sealed interface ")
                .append(polymorphic.javaTypeName())
                .append(" permits ")
                .append(String.join(", ", permitted))
                .append(" {\n");
        for (FieldSelection field : polymorphic.hoistedSharedFields()) {
            out.append("\n        ").append(fieldTypeAndName(field)).append("();\n");
        }
        out.append("    }\n\n");
    }

    private static void appendOutputEnumType(StringBuilder out, OutputEnumType type) {
        out.append("    public sealed interface ").append(type.javaTypeName()).append(" {\n\n");
        out.append("        enum Known implements ").append(type.javaTypeName()).append(" {\n");
        List<String> values = type.values();
        for (int i = 0; i < values.size(); i++) {
            out.append("            ").append(values.get(i));
            out.append(i < values.size() - 1 ? ",\n" : "\n");
        }
        out.append("        }\n\n");
        out.append("        record Unrecognized(String rawValue) implements ").append(type.javaTypeName()).append(" {}\n");
        out.append("    }\n\n");
    }

    /** A field's rendered type and Java identifier, e.g. {@code "@Nullable String name"}. */
    private static String fieldTypeAndName(FieldSelection field) {
        String identifier = JavaIdentifiers.fieldIdentifier(field.responseName());
        return JavaIdentifiers.nullableTypeReference(javaTypeNameFor(field.shape()), field.shape().nullable())
                + ' '
                + identifier;
    }

    private static String javaTypeNameFor(FieldShape shape) {
        return switch (shape) {
            case FieldShape.ScalarField scalar -> scalar.scalar().javaTypeName();
            case FieldShape.EnumField enumField -> enumField.enumType().javaTypeName();
            case FieldShape.ObjectField object -> object.selection().javaTypeName();
            case FieldShape.PolymorphicField polymorphic -> polymorphic.selection().javaTypeName();
            case FieldShape.ListField list ->
                    "List<" + nullablePrefixedTypeName(list.elementShape()) + ">";
        };
    }

    private static String nullablePrefixedTypeName(FieldShape shape) {
        return JavaIdentifiers.nullableTypeReference(javaTypeNameFor(shape), shape.nullable());
    }
}
