package dev.glisseo.izar.compiler.internal.generate;

import dev.glisseo.izar.compiler.internal.naming.JavaIdentifiers;
import dev.glisseo.izar.compiler.internal.naming.JavaLiterals;
import dev.glisseo.izar.compiler.internal.scalar.CustomScalarType;
import dev.glisseo.izar.compiler.internal.selection.FieldSelection;
import dev.glisseo.izar.compiler.internal.selection.FieldShape;
import dev.glisseo.izar.compiler.internal.selection.FragmentInterface;
import dev.glisseo.izar.compiler.internal.selection.ObjectSelection;
import dev.glisseo.izar.compiler.internal.selection.PolymorphicBranch;
import dev.glisseo.izar.compiler.internal.selection.PolymorphicSelection;
import dev.glisseo.izar.compiler.internal.variable.InputFieldDefinition;
import dev.glisseo.izar.compiler.internal.variable.InputObjectType;
import dev.glisseo.izar.compiler.internal.variable.InputShape;
import dev.glisseo.izar.compiler.internal.variable.VariableAnalyzer;
import dev.glisseo.izar.operation.GraphQlOperationKind;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.jspecify.annotations.Nullable;

/** Renders Spring GraphQL response models and request metadata without Izar's decoder contract. */
final class JacksonSourceGenerator {

    private JacksonSourceGenerator() {}

    static String generateFragmentInterface(String packageName, FragmentInterface fragmentInterface) {
        StringBuilder out = new StringBuilder();
        out.append("package ").append(packageName).append(";\n\n");
        out.append("import java.util.List;\n");
        out.append("import org.jspecify.annotations.NullMarked;\n");
        out.append("import org.jspecify.annotations.Nullable;\n\n");
        out.append("/** Generated by Izar from fragment '")
                .append(fragmentInterface.javaTypeName()).append("'. Do not edit. */\n");
        out.append("@NullMarked\n");
        out.append("public interface ").append(fragmentInterface.javaTypeName()).append(" {\n\n");
        List<FieldSelection> fields = fragmentInterface.fields();
        for (int i = 0; i < fields.size(); i++) {
            out.append("    ").append(fieldTypeAndNameForFragment(fields.get(i))).append("();\n");
            out.append(i < fields.size() - 1 ? "\n" : "");
        }
        out.append("}\n");
        return out.toString();
    }

    static String generate(
            String packageName,
            String className,
            String operationName,
            String documentText,
            String operationId,
            GraphQlOperationKind operationKind,
            ObjectSelection root,
            VariableAnalyzer.Result variables) {
        GeneratedSelections flattened = GeneratedSelections.from(root);
        List<CustomScalarType> inputScalars = InputSourceGenerator.collectCustomScalars(variables);
        boolean hasVariables = !variables.variables().isEmpty();
        boolean hasPolymorphicSelections = !flattened.polymorphicSelections().isEmpty();
        boolean hasAliasedFields = flattened.objectSelections().stream()
                .flatMap(type -> type.fields().stream())
                .anyMatch(field -> !JavaIdentifiers.fieldIdentifier(field.responseName()).equals(field.responseName()));

        StringBuilder out = new StringBuilder();
        out.append("package ").append(packageName).append(";\n\n");
        out.append("import dev.glisseo.izar.operation.GraphQlRequest;\n");
        out.append("import dev.glisseo.izar.operation.GraphQlOperationKind;\n");
        if (hasVariables || !variables.inputObjectTypes().isEmpty()) {
            out.append("import dev.glisseo.izar.operation.GraphQlEncoding;\n");
        }
        if (!inputScalars.isEmpty()) {
            out.append("import dev.glisseo.izar.operation.ScalarCodec;\n");
        }
        if (hasAliasedFields || hasSyntheticDiscriminator(flattened)) {
            out.append("import com.fasterxml.jackson.annotation.JsonProperty;\n");
        }
        if (hasPolymorphicSelections) {
            out.append("import com.fasterxml.jackson.annotation.JsonSubTypes;\n");
            out.append("import com.fasterxml.jackson.annotation.JsonTypeInfo;\n");
        }
        if (hasVariables || !variables.inputObjectTypes().isEmpty()) {
            out.append("import java.util.Collections;\n");
            out.append("import java.util.LinkedHashMap;\n");
        }
        if (hasListShape(flattened.objectSelections(), variables)) {
            out.append("import java.util.List;\n");
        }
        out.append("import java.util.Map;\n");
        out.append("import org.jspecify.annotations.NullMarked;\n");
        out.append("import org.jspecify.annotations.Nullable;\n");
        out.append('\n');
        out.append("/** Generated by Izar from operation '").append(operationName).append("'. Do not edit. */\n");
        out.append("@NullMarked\n");
        out.append("public final class ").append(className).append(" implements GraphQlRequest {\n\n");
        SourceGeneratorSupport.appendOperationConstants(out, operationName, documentText, operationId, operationKind);
        appendRootPathConstants(out, root);
        SourceGeneratorSupport.appendScalarCodecFields(out, inputScalars);
        if (hasVariables) {
            InputSourceGenerator.appendOperationVariableMembers(out, className, variables.variables());
        }

        SourceGeneratorSupport.appendOperationMethods(out, hasVariables);

        for (ObjectSelection type : flattened.objectSelections()) {
            appendRecord(out, type, flattened.implementsInterfaceByTypeName().get(type.javaTypeName()),
                    flattened.polymorphicByTypeName().get(type.javaTypeName()));
        }
        for (PolymorphicSelection polymorphic : flattened.polymorphicSelections()) {
            appendPolymorphicInterface(out, polymorphic);
        }
        for (var inputEnumType : variables.enumTypes()) {
            InputSourceGenerator.appendEnumType(out, inputEnumType);
        }
        for (InputObjectType inputObjectType : variables.inputObjectTypes()) {
            InputSourceGenerator.appendInputObjectType(out, inputObjectType);
        }
        out.append("}\n");
        return out.toString();
    }

    private static void appendRootPathConstants(StringBuilder out, ObjectSelection root) {
        Set<String> usedNames = new LinkedHashSet<>(List.of("OPERATION_NAME", "DOCUMENT", "OPERATION_ID", "OPERATION_KIND"));
        for (FieldSelection field : root.fields()) {
            String candidate = JavaIdentifiers.constantName(field.responseName());
            String name = candidate;
            int suffix = 2;
            while (!usedNames.add(name)) {
                name = candidate + suffix++;
            }
            out.append("    public static final String ").append(name).append(" = ")
                    .append(JavaLiterals.quote(field.responseName())).append(";\n");
        }
        out.append('\n');
    }

    private static boolean hasSyntheticDiscriminator(GeneratedSelections flattened) {
        return flattened.objectSelections().stream().anyMatch(type -> {
            PolymorphicSelection polymorphic = flattened.polymorphicByTypeName().get(type.javaTypeName());
            return polymorphic != null && type.fields().stream()
                    .noneMatch(field -> field.responseName().equals(polymorphic.discriminatorResponseKey()));
        });
    }

    private static boolean hasListShape(List<ObjectSelection> selections, VariableAnalyzer.Result variables) {
        boolean inOutput = selections.stream().flatMap(type -> type.fields().stream()).anyMatch(field -> hasListShape(field.shape()));
        boolean inVariables = variables.variables().stream().anyMatch(field -> hasListShape(field.shape()));
        boolean inInputs = variables.inputObjectTypes().stream().flatMap(type -> type.fields().stream())
                .anyMatch(field -> hasListShape(field.shape()));
        return inOutput || inVariables || inInputs;
    }

    private static boolean hasListShape(FieldShape shape) {
        return switch (shape) {
            case FieldShape.ListField ignored -> true;
            case FieldShape.ObjectField ignored -> false;
            case FieldShape.PolymorphicField ignored -> false;
            case FieldShape.ScalarField ignored -> false;
            case FieldShape.EnumField ignored -> false;
        };
    }

    private static boolean hasListShape(InputShape shape) {
        return switch (shape) {
            case InputShape.ListShape ignored -> true;
            case InputShape.ScalarShape ignored -> false;
            case InputShape.EnumShape ignored -> false;
            case InputShape.InputObjectShape ignored -> false;
        };
    }

    private static void appendRecord(
            StringBuilder out,
            ObjectSelection type,
            @Nullable String polymorphicInterface,
            @Nullable PolymorphicSelection polymorphic) {
        List<FieldSelection> fields = type.fields();
        boolean hasSyntheticDiscriminator = polymorphic != null && fields.stream()
                .noneMatch(field -> field.responseName().equals(polymorphic.discriminatorResponseKey()));
        out.append("    public record ").append(type.javaTypeName()).append('(');
        out.append(fields.isEmpty() && !hasSyntheticDiscriminator ? "" : "\n");
        for (int i = 0; i < fields.size(); i++) {
            out.append("            ").append(fieldTypeAndName(fields.get(i)));
            out.append(i < fields.size() - 1 || hasSyntheticDiscriminator ? ",\n" : "\n");
        }
        if (hasSyntheticDiscriminator) {
            appendDiscriminatorComponent(out, polymorphic.discriminatorResponseKey());
        }
        out.append(fields.isEmpty() && !hasSyntheticDiscriminator ? "" : "    ");
        out.append(')');
        List<String> interfaces = new ArrayList<>(type.implementsFragments());
        if (polymorphicInterface != null) {
            interfaces.add(polymorphicInterface);
        }
        if (!interfaces.isEmpty()) {
            out.append(" implements ").append(String.join(", ", interfaces));
        }
        out.append(" {}\n\n");
    }

    private static void appendDiscriminatorComponent(StringBuilder out, String key) {
        String identifier = JavaIdentifiers.fieldIdentifier(key);
        out.append("            ");
        if (!key.equals(identifier)) {
            out.append("@JsonProperty(").append(JavaLiterals.quote(key)).append(") ");
        }
        out.append("String ").append(identifier).append('\n');
    }

    private static void appendPolymorphicInterface(StringBuilder out, PolymorphicSelection polymorphic) {
        List<String> permitted = new ArrayList<>();
        for (PolymorphicBranch branch : polymorphic.branches()) {
            permitted.add(branch.selection().javaTypeName());
        }
        permitted.add(polymorphic.unrecognizedBranch().javaTypeName());
        out.append("    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXISTING_PROPERTY, property = ")
                .append(JavaLiterals.quote(polymorphic.discriminatorResponseKey()))
                .append(", visible = true, defaultImpl = ")
                .append(polymorphic.unrecognizedBranch().javaTypeName()).append(".class)\n");
        out.append("    @JsonSubTypes({\n");
        for (int i = 0; i < polymorphic.branches().size(); i++) {
            PolymorphicBranch branch = polymorphic.branches().get(i);
            out.append("        @JsonSubTypes.Type(value = ").append(branch.selection().javaTypeName())
                    .append(".class, name = ").append(JavaLiterals.quote(branch.graphqlTypeName()))
                    .append(i < polymorphic.branches().size() - 1 ? "),\n" : ")\n");
        }
        out.append("    })\n");
        out.append("    public sealed interface ").append(polymorphic.javaTypeName())
                .append(" permits ").append(String.join(", ", permitted)).append(" {\n");
        for (FieldSelection field : polymorphic.hoistedSharedFields()) {
            out.append("\n        ").append(fieldTypeAndNameForFragment(field)).append("();\n");
        }
        out.append("    }\n\n");
    }

    private static String fieldTypeAndName(FieldSelection field) {
        String identifier = JavaIdentifiers.fieldIdentifier(field.responseName());
        String propertyAnnotation = identifier.equals(field.responseName())
                ? ""
                : "@JsonProperty(" + JavaLiterals.quote(field.responseName()) + ") ";
        return propertyAnnotation + JavaIdentifiers.nullableTypeReference(javaTypeNameFor(field.shape()), field.shape().nullable())
                + ' ' + identifier;
    }

    private static String fieldTypeAndNameForFragment(FieldSelection field) {
        return JavaIdentifiers.nullableTypeReference(javaTypeNameFor(field.shape()), field.shape().nullable())
                + ' '
                + JavaIdentifiers.fieldIdentifier(field.responseName());
    }

    private static String javaTypeNameFor(FieldShape shape) {
        return switch (shape) {
            case FieldShape.ScalarField scalar -> scalar.scalar().javaTypeName();
            case FieldShape.EnumField ignored -> "String";
            case FieldShape.ObjectField object -> object.selection().javaTypeName();
            case FieldShape.PolymorphicField polymorphic -> polymorphic.selection().javaTypeName();
            case FieldShape.ListField list -> "List<" + nullablePrefixedTypeName(list.elementShape()) + ">";
        };
    }

    private static String nullablePrefixedTypeName(FieldShape shape) {
        return JavaIdentifiers.nullableTypeReference(javaTypeNameFor(shape), shape.nullable());
    }
}
